apiVersion: v1
appVersion: 2.7.1
description: A Helm chart for Rocketmq Exporter
home: https://hub.docker.com/
icon: https://hub.docker.com/public/images/logos/mini-logo.svg
maintainers:
- email: wangqinghui9@jd.com
  name: wangqinghui9
name: rocketmq-exporter
sources:
- https://github.com/docker/distribution-library-image
version: 0.0.1